### ISSUE TITLE
Timeout before scraping

### ISSUE THREAD

**Issue by lisandro52** [pietrovismara/scavenger#4]
Hey! It's me again. I've been heavily using your library, and it's been awesome all along. But now I've hit another wall: Sometimes, stuff loads async on the browser, like products' information and prices.
Is there something available to tell nightmare to wait X seconds before doing the scrape?

Thanks for all, and keep up the good work!

**Comment by pietrovismara** [comment]
Instead of waiting x seconds (which is pretty unreliable since you cannot predict the page loading time) you can wait for that element to be rendered, using the `selector` option when calling `.scrape` or `.screenshot`.

For example if the product information you need is contained inside an element with id #product, you will pass `#product` as selector option.

Another way would be to experiment with the `driverFn` option, calling `this.wait(milliseconds)` from it, which would make nightmarejs wait before scraping the page.

You can find more info on these options in [the docs](https://github.com/pietrovismara/scavenger#api).

**Comment by pietrovismara** [comment]
@lisandro52 closing as it doesn't look like there's a bug or a missing feature here. 
If needed please reopen the issue and add information.
